version: '2'

services:

  crudular-angular:
    build:
      context: .
      dockerfile: ./.docker/crudular-angular.production.dockerfile
    command: ng build -prod
    container_name: crudular-angular-build-prod
    image: crudular-angular
    networks:
      - prod-network
    volumes:
      - ./dist:/home/app/crudular/dist

  crudular-nginx:
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/crudular.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: crudular-nginx
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    image: nginx
    networks:
      - prod-network
    ports:
     - "8080:80"
    volumes:
     - ./.docker/nginx.conf:/etc/nginx/conf.d/crudular.template
     - ./dist:/var/www/dist/prod

networks:
  prod-network:
    driver: bridge
