version: '2'

services:

  dist-build:
    container_name: dist-build
    image: dist-build
    build:
      context: .
      dockerfile: ./.docker/dist-build.production.dockerfile
    ports:
      - '4200:4200'
    networks:
      - dist-network

  nginx:
    container_name: nginx
    image: nginx
    volumes:
     - ./.docker/nginx.conf:/etc/nginx/conf.d/crudular.template
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/crudular.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - dist-network

networks:
  dist-network:
    driver: bridge
